project:
  type: book
  output-dir: docs
  resources:
    - images

book:
  title: "AI Foundry Lab"
  author: "Scott Murff"
  date: "9/2/2026"
  favicon: images/favicon.svg
  chapters:
    - index.qmd
    - part: The AI Foundry
      chapters:
        - students/00-constitution.qmd
        - students/00-client-selection.qmd
        - students/06-builder-and-consultant.qmd
        - students/07-resources.qmd

    - part: The Course
      chapters:
        - students/01-syllabus.qmd
        - students/02-getting-started.qmd
    - part: On a Client Team
      chapters:
        - students/05-how-teams-are-staffed.qmd
        - students/03-weekly-updates.qmd
        - students/04-build-standards.qmd

format:
  html:
    include-in-header: _header.html
    include-after-body: _footer.html
    theme: cosmo
    link-external-icon: false
    link-external-newwindow: false
    css: styles.css
    markdown: default
    toc-title: On this page

number-sections: false
