<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Scott Murff">
<meta name="dcterms.date" content="2026-09-02">

<title>Syllabus – AI Foundry Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../students/02-getting-started.html" rel="next">
<link href="../students/07-resources.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head><body class="nav-sidebar floating quarto-light"><header class="book-header-banner">
  <a href="https://aifoundry.byu.edu" target="_blank">
    <img src="https://ai-foundry-byu.github.io/foundry-lab/images/byu-marriott-ai-foundry.png" alt="BYU Marriott School of Business, AI Foundry">
  </a>
</header>

<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5TPMPSE4HZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5TPMPSE4HZ');
</script>

<!-- Sidebar title: add cross-listed course numbers -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var title = document.querySelector('.sidebar-title');
    if (!title) return;

    if (!document.querySelector('.sidebar-course-numbers')) {
      var nums = document.createElement('div');
      nums.className = 'sidebar-course-numbers';
      nums.textContent = 'MBA 693R · STRAT 490R';
      title.insertAdjacentElement('afterend', nums);
    }
  });
</script>

<!-- Draft watermark on every page except the resources page -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (!/07-resources/.test(window.location.pathname)) {
      document.body.classList.add('draft-page');
    }
  });
</script>


<link rel="stylesheet" href="../styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../students/01-syllabus.html">The Course</a></li><li class="breadcrumb-item"><a href="../students/01-syllabus.html"><span class="chapter-title">Syllabus</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">AI Foundry Lab</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">The AI Foundry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/00-constitution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Constitution and Operating Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/00-client-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Client Service Selection Policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/06-builder-and-consultant.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Builder and the Consultant</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/07-resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Resources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The Course</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/01-syllabus.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/02-getting-started.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Getting Started</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">On a Client Team</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/05-how-teams-are-staffed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Teams Are Staffed</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/03-weekly-updates.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Weekly Updates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../students/04-build-standards.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Build Standards</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-numbers" id="toc-course-numbers" class="nav-link active" data-scroll-target="#course-numbers">Course Numbers</a></li>
  <li><a href="#what-this-course-is" id="toc-what-this-course-is" class="nav-link" data-scroll-target="#what-this-course-is">What This Course Is</a></li>
  <li><a href="#what-you-give-and-what-you-get" id="toc-what-you-give-and-what-you-get" class="nav-link" data-scroll-target="#what-you-give-and-what-you-get">What You Give and What You Get</a>
  <ul class="collapse">
  <li><a href="#what-you-give" id="toc-what-you-give" class="nav-link" data-scroll-target="#what-you-give">What you give</a></li>
  <li><a href="#what-you-get" id="toc-what-you-get" class="nav-link" data-scroll-target="#what-you-get">What you get</a></li>
  <li><a href="#how-stipends-are-calculated" id="toc-how-stipends-are-calculated" class="nav-link" data-scroll-target="#how-stipends-are-calculated">How stipends are calculated</a></li>
  <li><a href="#where-the-money-goes" id="toc-where-the-money-goes" class="nav-link" data-scroll-target="#where-the-money-goes">Where the money goes</a></li>
  </ul></li>
  <li><a href="#studio-time" id="toc-studio-time" class="nav-link" data-scroll-target="#studio-time">Studio Time</a></li>
  <li><a href="#how-you-are-assessed" id="toc-how-you-are-assessed" class="nav-link" data-scroll-target="#how-you-are-assessed">How You Are Assessed</a></li>
  <li><a href="#grading" id="toc-grading" class="nav-link" data-scroll-target="#grading">Grading</a>
  <ul class="collapse">
  <li><a href="#grade-components-500-points-possible" id="toc-grade-components-500-points-possible" class="nav-link" data-scroll-target="#grade-components-500-points-possible">Grade Components (500 points possible)</a></li>
  <li><a href="#weekly-update-emails-56-points" id="toc-weekly-update-emails-56-points" class="nav-link" data-scroll-target="#weekly-update-emails-56-points">Weekly Update Emails (56 points)</a></li>
  <li><a href="#milestone-deliverables-160-points" id="toc-milestone-deliverables-160-points" class="nav-link" data-scroll-target="#milestone-deliverables-160-points">Milestone Deliverables (160 points)</a></li>
  <li><a href="#client-evaluation-64-points" id="toc-client-evaluation-64-points" class="nav-link" data-scroll-target="#client-evaluation-64-points">Client Evaluation (64 points)</a></li>
  <li><a href="#developmentship-180-points" id="toc-developmentship-180-points" class="nav-link" data-scroll-target="#developmentship-180-points">Developmentship (180 points)</a></li>
  <li><a href="#video-reflection-40-points" id="toc-video-reflection-40-points" class="nav-link" data-scroll-target="#video-reflection-40-points">Video Reflection (40 points)</a></li>
  <li><a href="#extra-credit-10-points" id="toc-extra-credit-10-points" class="nav-link" data-scroll-target="#extra-credit-10-points">Extra Credit (10 points)</a></li>
  <li><a href="#grading-scale" id="toc-grading-scale" class="nav-link" data-scroll-target="#grading-scale">Grading Scale</a></li>
  </ul></li>
  <li><a href="#credit-hours" id="toc-credit-hours" class="nav-link" data-scroll-target="#credit-hours">Credit Hours</a></li>
  <li><a href="#confidentiality-and-client-data" id="toc-confidentiality-and-client-data" class="nav-link" data-scroll-target="#confidentiality-and-client-data">Confidentiality and Client Data</a></li>
  <li><a href="#ai-use-policy" id="toc-ai-use-policy" class="nav-link" data-scroll-target="#ai-use-policy">AI Use Policy</a></li>
  <li><a href="#instructor-bio" id="toc-instructor-bio" class="nav-link" data-scroll-target="#instructor-bio">Instructor Bio</a></li>
  <li><a href="#getting-help" id="toc-getting-help" class="nav-link" data-scroll-target="#getting-help">Getting Help</a></li>
  <li><a href="#mission-and-aims" id="toc-mission-and-aims" class="nav-link" data-scroll-target="#mission-and-aims">Mission and Aims</a></li>
  <li><a href="#honor-code" id="toc-honor-code" class="nav-link" data-scroll-target="#honor-code">Honor Code</a></li>
  <li><a href="#preventing-responding-to-sexual-misconduct" id="toc-preventing-responding-to-sexual-misconduct" class="nav-link" data-scroll-target="#preventing-responding-to-sexual-misconduct">Preventing &amp; Responding to Sexual Misconduct</a></li>
  <li><a href="#student-disability" id="toc-student-disability" class="nav-link" data-scroll-target="#student-disability">Student Disability</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../students/01-syllabus.html">The Course</a></li><li class="breadcrumb-item"><a href="../students/01-syllabus.html"><span class="chapter-title">Syllabus</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Syllabus</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Scott Murff </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="course-numbers-page">
<p>MBA 693R · STRAT 490R</p>
</div>
<p><em>FALL 2026 – WINTER 2027</em></p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><strong>Instructor</strong></td>
<td>Scott Murff</td>
</tr>
<tr class="even">
<td><strong>Class Time</strong></td>
<td>Fridays, 8:00–11:50 AM</td>
</tr>
<tr class="odd">
<td><strong>Class Location</strong></td>
<td>2140 TNRB</td>
</tr>
<tr class="even">
<td><strong>Office Hours</strong></td>
<td>Fridays, 11:00 AM–12:00 PM</td>
</tr>
<tr class="odd">
<td><strong>LMS</strong></td>
<td>Canvas</td>
</tr>
</tbody>
</table>
<section id="course-numbers" class="level2">
<h2 class="anchored" data-anchor-id="course-numbers">Course Numbers</h2>
<p>This course is cross-listed under two course numbers. It is all the same class: everyone meets together Fridays 8:00 to 11:50 AM in 2140 TNRB, works on the same client teams, uses this site, and uses Canvas as the LMS. Register under whichever number fits your program.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Course</th>
<th>Section</th>
<th>Title</th>
<th>Credit Hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MBA 693R</td>
<td>011</td>
<td>Special Topics in Management</td>
<td>3.0</td>
</tr>
<tr class="even">
<td>STRAT 490R</td>
<td>001</td>
<td>Topics in Strategic Management</td>
<td>3.0</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Canvas</strong> is used only for submitting milestone deliverables and your final video reflection, and for reviewing grades. All other course content lives on this website.</p>
</div>
</div>
</section>
<section id="what-this-course-is" class="level2">
<h2 class="anchored" data-anchor-id="what-this-course-is">What This Course Is</h2>
<p>The AI Foundry is an AI-native product studio and consultancy. You are on a delivery team for a paying client. The client is paying a fixed fee, retains the intellectual property, and expects professional work. Your grade reflects both the quality of what you ship and the professionalism with which you ship it.</p>
<p>We ship, not advise. Discovery work is real and comes first, but it exists to point at something to build. Every engagement ends with software running in the client’s hands, not with a deck.</p>
<p>This is a two-semester course. You enroll each semester. Engagements are accepted on a rolling basis, so your team’s phase boundaries come from your kick-off rather than from a course-wide calendar.</p>
</section>
<section id="what-you-give-and-what-you-get" class="level2">
<h2 class="anchored" data-anchor-id="what-you-give-and-what-you-get">What You Give and What You Get</h2>
<p>Joining the Foundry is a trade, and both sides of it are written down here so nobody has to guess.</p>
<section id="what-you-give" class="level3">
<h3 class="anchored" data-anchor-id="what-you-give">What you give</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Base commitment</strong></td>
<td>10 hours per week, including the Friday studio block</td>
</tr>
<tr class="even">
<td><strong>Surge commitment</strong></td>
<td>Typically an additional 10 hours per week when client demand calls for it</td>
</tr>
<tr class="odd">
<td><strong>Your tools</strong></td>
<td>You carry your own frontier AI subscriptions</td>
</tr>
<tr class="even">
<td><strong>Your time horizon</strong></td>
<td>Two semesters, fall and winter</td>
</tr>
</tbody>
</table>
<p>The base 10 hours is the course. The surge hours are what real client delivery costs when a deadline is real and the client is paying. Surge is not every week, and it is not open-ended, but it is not optional either when your team is in it.</p>
</section>
<section id="what-you-get" class="level3">
<h3 class="anchored" data-anchor-id="what-you-get">What you get</h3>
<p><strong>Three credits per semester, six across the year.</strong> The credit is the compensation for the base 10 hours. That is the academic side of the trade, and it is guaranteed whether or not your engagement is a funded one.</p>
<p><strong>A stipend for the surge hours.</strong> Credit pays for the base. Cash pays for the hours above it. Foundry engagements are paid for by the client, and a defined share of that revenue comes back to the students who did the work.</p>
<p><strong>Real work you can point at.</strong> Production software running in a company’s hands, shipped under your name, with a client who will take your call.</p>
</section>
<section id="how-stipends-are-calculated" class="level3">
<h3 class="anchored" data-anchor-id="how-stipends-are-calculated">How stipends are calculated</h3>
<p>Two inputs, and only two.</p>
<ol type="1">
<li><strong>The size of the stipend pool</strong>, which is a published share of total Foundry revenue for the year. See the allocation table below.</li>
<li><strong>Your utilization</strong>, which is your logged, verified hours on funded client work as a share of all such hours across the Foundry that term.</li>
</ol>
<p>Your stipend is your utilization share of the pool. If you carried twice the load of a teammate, you receive twice the stipend. Hours are logged weekly and confirmed by your team, and hours that are not logged do not count.</p>
<p>A few things to be clear about:</p>
<ul>
<li>The stipend follows funded work. Students staffed only on pro bono or internal work in a given term do not draw from the pool for those hours.</li>
<li>It is applied to your student account.</li>
<li>This is a stipend, not employment. You are not an hourly employee of the university or of the client, and the stipend is not a wage or a guaranteed rate.</li>
<li>Money applied to a student account can interact with a financial aid package. If you receive need-based aid, check with the financial aid office before assuming it is additive.</li>
</ul>
</section>
<section id="where-the-money-goes" class="level3">
<h3 class="anchored" data-anchor-id="where-the-money-goes">Where the money goes</h3>
<p>Not every dollar the Foundry earns goes back to Foundry members, and you should know what the other dollars do. Revenue is allocated as a published waterfall:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Claim</th>
<th>Share</th>
<th>Why it exists</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Strategy program</td>
<td>30%</td>
<td>The Foundry sits inside the BYU strategy program, which provides the faculty, the classroom, the accreditation, and the students. The Foundry funds it back.</td>
</tr>
<tr class="even">
<td>Reserve</td>
<td>10%</td>
<td>Down years. A studio that cannot survive a slow semester cannot make commitments to clients or to you.</td>
</tr>
<tr class="odd">
<td>Program operations</td>
<td>10%</td>
<td>Events, swag, travel to client sites and competitions</td>
</tr>
<tr class="even">
<td><strong>Student stipend pool</strong></td>
<td><strong>The remainder, never less than 50%</strong></td>
<td><strong>You</strong></td>
</tr>
</tbody>
</table>
<p>The strategy program share is capped. The annual amount is set and published before the year begins, and once it is met, every additional dollar of that 30% flows into the student stipend pool instead. The cap is the point. The Foundry funds the program that houses it, and then it stops taking.</p>
<p>These percentages are set for the year and published before engagements are staffed. They are not adjusted after the fact.</p>
</section>
</section>
<section id="studio-time" class="level2">
<h2 class="anchored" data-anchor-id="studio-time">Studio Time</h2>
<p>The Friday 8:00 to 11:50 AM block in 2140 TNRB is your team’s standing work session: co-working, cross-team critique, client calls, and office hours with Professor Murff.</p>
<p><strong>Required sessions:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 60%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Session</th>
<th>When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kick-off, team formation, client introductions</td>
<td>First studio of fall semester</td>
</tr>
<tr class="even">
<td>Phase review: discovery</td>
<td>Set per engagement</td>
</tr>
<tr class="odd">
<td>Phase review: build</td>
<td>Set per engagement</td>
</tr>
<tr class="even">
<td>Phase review: transfer and handoff</td>
<td>Set per engagement</td>
</tr>
<tr class="odd">
<td>End-of-year showcase</td>
<td>Final studio of winter semester</td>
</tr>
</tbody>
</table>
<p>Engagements start on a rolling basis, so phase reviews are scheduled per team rather than on a single course calendar. Your team’s review dates are set at kick-off and posted in Canvas.</p>
<p>All other Fridays are optional but strongly encouraged. Teams that skip studio time consistently underperform.</p>
</section>
<section id="how-you-are-assessed" class="level2">
<h2 class="anchored" data-anchor-id="how-you-are-assessed">How You Are Assessed</h2>
<p>Two instruments run alongside the point total, and they measure different things in different ways.</p>
<p><strong>The Builder</strong>, six axes: Discovery, Design, Application Architecture, AI Systems, Agentic Workflow, and Launch and Learn. You self-report these at the start of fall semester and again in December. They are <strong>not graded</strong>. They exist so you can see your own profile, so teams can be staffed for coverage, and so the program can tell whether the year moved you.</p>
<p><strong>The Consultant</strong>, four axes: Workstream Ownership, Client Presence, Communication, and Collaboration. These are what changes when the work belongs to someone else, and they are <strong>not self-reported</strong>. The faculty advisor and your teammates rate them against observed behavior at midterm and at the end of each semester, using the same 1 to 5 scale with written behavioral anchors.</p>
<p>The Consultant diamond is the <strong>Developmentship</strong> component below, worth 180 of 500 points. It is the largest single input to your grade and the only one that is purely individual. How ratings are gathered, weighted, and converted to points is set out in the Developmentship Model.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Builder</th>
<th>Consultant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What it measures</strong></td>
<td>What you can make</td>
<td>What changes when the work is for someone else</td>
</tr>
<tr class="even">
<td><strong>Who rates it</strong></td>
<td>You</td>
<td>Faculty and teammates</td>
</tr>
<tr class="odd">
<td><strong>When</strong></td>
<td>September and December</td>
<td>Midterm and end of term</td>
</tr>
<tr class="even">
<td><strong>Graded</strong></td>
<td>No</td>
<td>Feeds two existing components</td>
</tr>
</tbody>
</table>
</section>
<section id="grading" class="level2">
<h2 class="anchored" data-anchor-id="grading">Grading</h2>
<p>Grades are based on weekly update emails, four milestone deliverables, client evaluation, peer evaluation, and a video reflection.</p>
<section id="grade-components-500-points-possible" class="level3">
<h3 class="anchored" data-anchor-id="grade-components-500-points-possible">Grade Components (500 points possible)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Points</th>
<th>Weight</th>
<th>Level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Weekly Update Emails</td>
<td>56 pts</td>
<td>11%</td>
<td>Individual</td>
</tr>
<tr class="even">
<td>Milestone Deliverables</td>
<td>160 pts</td>
<td>32%</td>
<td>Team</td>
</tr>
<tr class="odd">
<td>Client Evaluation</td>
<td>64 pts</td>
<td>13%</td>
<td>Team</td>
</tr>
<tr class="even">
<td>Developmentship</td>
<td>180 pts</td>
<td>36%</td>
<td>Individual</td>
</tr>
<tr class="odd">
<td>Video Reflection</td>
<td>40 pts</td>
<td>8%</td>
<td>Individual</td>
</tr>
<tr class="even">
<td><strong>Base Total</strong></td>
<td><strong>500 pts</strong></td>
<td>100%</td>
<td></td>
</tr>
<tr class="odd">
<td>Extra Credit (BYU Student Ratings)</td>
<td>10 pts</td>
<td>+2%</td>
<td></td>
</tr>
</tbody>
</table>
<p>Two components grade the <strong>product and the pod</strong>: milestones and the client’s evaluation of the team, 224 points between them. Three grade <strong>you</strong>: your updates, your developmentship composite, and your reflection, 276 points. A pod that ships well cannot carry a passenger to an A, and a strong individual on a struggling pod is not sunk by it.</p>
</section>
<section id="weekly-update-emails-56-points" class="level3">
<h3 class="anchored" data-anchor-id="weekly-update-emails-56-points">Weekly Update Emails (56 points)</h3>
<p>28 emails across two semesters, 2 points each.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Status</th>
<th>Points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>On time (Saturday by 11:59 PM)</td>
<td>2 pts</td>
</tr>
<tr class="even">
<td>Late (by Monday 12:00 PM noon)</td>
<td>1 pt</td>
</tr>
<tr class="odd">
<td>After Monday noon</td>
<td>0 pts</td>
</tr>
</tbody>
</table>
<p>This component scores <strong>compliance only</strong>: whether the update arrived, on time. Whether it was any good is graded on the Communication axis of your developmentship composite, from the same emails, by the people who had to read them. See <a href="../students/03-weekly-updates.html">Weekly Updates</a>.</p>
</section>
<section id="milestone-deliverables-160-points" class="level3">
<h3 class="anchored" data-anchor-id="milestone-deliverables-160-points">Milestone Deliverables (160 points)</h3>
<p>Four milestones, 40 points each. These are graded by the faculty advisor against the <a href="../students/04-build-standards.html">Build Standards</a>, not by the client.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Milestone</th>
<th>What is due</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>D: Discovery</strong></td>
<td>An AI-specific audit of the client’s business. Where AI actually helps them, what is worth building, what is worth automating, with an estimate and a sequence. Client signs off.</td>
</tr>
<tr class="even">
<td><strong>B1: Working build</strong></td>
<td>Software that runs, integrated with the client’s systems or a realistic stand-in, with the architecture documented</td>
</tr>
<tr class="odd">
<td><strong>B2: Shipped</strong></td>
<td>Production code running in the client’s environment. Tested, deployed, monitored</td>
</tr>
<tr class="even">
<td><strong>T: Transfer</strong></td>
<td>Handoff documentation, a walkthrough with the client’s own people, and a repository they can run without us</td>
</tr>
</tbody>
</table>
<p>Milestone due dates are set per engagement at kick-off and posted in Canvas. Teams on a discovery-only engagement complete D and a scaled transfer; teams on a full engagement complete all four.</p>
<p>Each milestone is scored on four dimensions, 10 points each:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>What earns full marks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Correctness</strong></td>
<td>It works. Analysis reconciles, code does what it claims, assumptions are stated and defensible.</td>
</tr>
<tr class="even">
<td><strong>Usefulness</strong></td>
<td>Someone at the client would actually use it. It solves the problem they have.</td>
</tr>
<tr class="odd">
<td><strong>Explainability</strong></td>
<td>Someone outside the team can follow how it works and why it does what it does.</td>
</tr>
<tr class="even">
<td><strong>Craft</strong></td>
<td>Clean repository, readable code, tests where they matter, documents proofread, professional presentation.</td>
</tr>
</tbody>
</table>
</section>
<section id="client-evaluation-64-points" class="level3">
<h3 class="anchored" data-anchor-id="client-evaluation-64-points">Client Evaluation (64 points)</h3>
<p>Your client evaluates the <strong>team</strong> twice: at mid-term for development only, and at the end of the year as an input to your grade. Five dimensions, 1 to 5, each with written behavioral descriptions the client can point at. Faculty sends the same questionnaire both times, and you see the results.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>The question the client answers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timeliness</td>
<td>Did the team deliver what they promised, when they promised it?</td>
</tr>
<tr class="even">
<td>Communication</td>
<td>Could you tell where the work stood without chasing anyone?</td>
</tr>
<tr class="odd">
<td>Agency</td>
<td>Did the team move the work forward on its own?</td>
</tr>
<tr class="even">
<td>Technical Competency</td>
<td>Did they build something that actually works?</td>
</tr>
<tr class="odd">
<td>Contribution</td>
<td>Was the output worth the engagement?</td>
</tr>
</tbody>
</table>
<p>The five dimensions are averaged, and the average converts to points:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Team average</th>
<th>Points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4.75 to 5.00</td>
<td>64</td>
</tr>
<tr class="even">
<td>4.50 to 4.74</td>
<td>62</td>
</tr>
<tr class="odd">
<td>4.25 to 4.49</td>
<td>60</td>
</tr>
<tr class="even">
<td>4.00 to 4.24</td>
<td>58</td>
</tr>
<tr class="odd">
<td>3.75 to 3.99</td>
<td>55</td>
</tr>
<tr class="even">
<td>3.50 to 3.74</td>
<td>53</td>
</tr>
<tr class="odd">
<td>3.25 to 3.49</td>
<td>51</td>
</tr>
<tr class="even">
<td>3.00 to 3.24</td>
<td>49</td>
</tr>
<tr class="odd">
<td>2.75 to 2.99</td>
<td>47</td>
</tr>
<tr class="even">
<td>2.50 to 2.74</td>
<td>45</td>
</tr>
<tr class="odd">
<td>2.00 to 2.49</td>
<td>40</td>
</tr>
<tr class="even">
<td>Below 2.00</td>
<td>Reviewed individually</td>
</tr>
</tbody>
</table>
<p><strong>This score is the same for everyone on the pod.</strong> The client also answers a short set of questions about each of you individually, and those feed your developmentship composite rather than this component.</p>
</section>
<section id="developmentship-180-points" class="level3">
<h3 class="anchored" data-anchor-id="developmentship-180-points">Developmentship (180 points)</h3>
<p>This is the individual instrument, and it is the largest single component of your grade. It scores the four Consultant axes: Workstream Ownership, Collaboration, Communication, and Client Presence.</p>
<p><strong>Three surveys, one question set.</strong> You are rated from three directions, and every form is built from the same underlying questions asked from the vantage that rater actually has.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 40%">
<col style="width: 20%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Survey</th>
<th>Who fills it</th>
<th>Rates</th>
<th>When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Self-Assessment</strong></td>
<td>You</td>
<td>All four axes. <strong>Not in your composite</strong></td>
<td>Closes first, before you see anything</td>
</tr>
<tr class="even">
<td><strong>Peer Evaluation</strong></td>
<td>Every Foundry member who saw your work</td>
<td>All four axes</td>
<td>Opens after self closes</td>
</tr>
<tr class="odd">
<td><strong>Client Evaluation</strong></td>
<td>Every client contact you worked with</td>
<td>Client Presence, Communication, and Ownership. Never Collaboration</td>
<td>In parallel, sees neither</td>
</tr>
</tbody>
</table>
<p>The ordering is deliberate. A self-rating collected after you have read your reviews measures nothing.</p>
<p><strong>You do not choose your reviewers.</strong> Two weeks before the end of each semester you submit an exposure list naming everyone who saw your work, and faculty adds anyone the staffing records show you worked with.</p>
<p><strong>How several reviewers become one number.</strong> Ratings are not thrown into a single average, because six teammates and one client would let your pod outvote the person paying for the work. Three passes:</p>
<p><em>First,</em> ratings are averaged <strong>within each source</strong>, weighted by how much of your work that person saw.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Exposure</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deep. Same engagement, most weeks, most of the semester</td>
<td>3</td>
</tr>
<tr class="even">
<td>Moderate. Part of the term, or regular contact on another engagement</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Light. A handful of interactions</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><em>Second,</em> the peer, client, and faculty scores are <strong>combined per axis</strong>, weighted by what that source can actually see:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Axis</th>
<th>Peers</th>
<th>Client</th>
<th>Faculty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Workstream Ownership</td>
<td>50%</td>
<td>20%</td>
<td>30%</td>
</tr>
<tr class="even">
<td>Collaboration</td>
<td>60%</td>
<td>none</td>
<td>40%</td>
</tr>
<tr class="odd">
<td>Communication</td>
<td>40%</td>
<td>35%</td>
<td>25%</td>
</tr>
<tr class="even">
<td>Client Presence</td>
<td>25%</td>
<td>50%</td>
<td>25%</td>
</tr>
</tbody>
</table>
<p>If a source is missing, the remaining weights scale up. You are never penalized for a rater who did not exist, which is what makes a discovery-only engagement gradeable.</p>
<p><em>Third,</em> the four axis scores are averaged equally into your composite.</p>
<p><strong>Extreme ratings require evidence.</strong> A 5, a 1, or a 2 submitted without a specific instance behind it is dropped rather than averaged in. This applies in both directions.</p>
<p><strong>Your self-assessment is never in your composite.</strong> It is compared against it and reported to you as a calibration gap. The gap does not move your grade. What it does is set up your video reflection, which is where self-awareness is actually graded.</p>
<p>The four axis scores are averaged, and the composite converts to points:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Composite</th>
<th>Points</th>
<th>Equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4.75 to 5.00</td>
<td>180</td>
<td>100%</td>
</tr>
<tr class="even">
<td>4.50 to 4.74</td>
<td>173</td>
<td>96%</td>
</tr>
<tr class="odd">
<td>4.25 to 4.49</td>
<td>168</td>
<td>93%</td>
</tr>
<tr class="even">
<td>4.00 to 4.24</td>
<td>162</td>
<td>90%</td>
</tr>
<tr class="odd">
<td>3.75 to 3.99</td>
<td>156</td>
<td>87%</td>
</tr>
<tr class="even">
<td>3.50 to 3.74</td>
<td>150</td>
<td>83%</td>
</tr>
<tr class="odd">
<td>3.25 to 3.49</td>
<td>144</td>
<td>80%</td>
</tr>
<tr class="even">
<td>3.00 to 3.24</td>
<td>138</td>
<td>77%</td>
</tr>
<tr class="odd">
<td>2.75 to 2.99</td>
<td>131</td>
<td>73%</td>
</tr>
<tr class="even">
<td>2.50 to 2.74</td>
<td>126</td>
<td>70%</td>
</tr>
<tr class="odd">
<td>2.00 to 2.49</td>
<td>113</td>
<td>63%</td>
</tr>
<tr class="even">
<td>Below 2.00</td>
<td>Reviewed individually</td>
<td></td>
</tr>
</tbody>
</table>
<p>Read this against the anchors and the standard is plain. <strong>A 3 is a reliable teammate who does what is asked</strong>, and in a graduate course that converts at 77%. <strong>A 4 is someone who owns a workstream, makes their team better, writes something a stakeholder can act on, and can be put in front of a client.</strong> That is the expectation, and it converts at 90%. Above 4.5 is rare on purpose.</p>
<p><strong>There is no curve.</strong> This table is published in week 1 and does not move. If everyone in the section earns a 4.5, everyone gets an A. Excellence over everything is the first principle in our constitution, and grading you against your classmates would contradict it. It would also make helping the person next to you cost you something, which is the one thing Collaboration cannot survive.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Two rules override the point total.</strong></p>
<ul>
<li>A composite <strong>below 3.00</strong> caps the course grade at <strong>B</strong>, whatever the team components say.</li>
<li>A rating of <strong>1 on any axis from two or more independent reviewers</strong> caps the course grade at <strong>B-</strong>. The axes are not tradeable at the bottom.</li>
</ul>
<p>A composite below 2.00 is reviewed individually and a failing grade is available. A confidentiality breach or anything failing the red face test leaves this model entirely and becomes a conduct matter.</p>
</div>
</div>
<p><strong>A practice round runs at midterm.</strong> It carries no points. It exists so that nothing in the final round is new information, and so you still have a semester to act on what you hear.</p>
<p><strong>You receive a development summary,</strong> not just a number: your four axis scores, the themes across everyone who reviewed you, where sources disagreed, and the two things to work on next. Individual comments are never attributed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Developmentship has nothing to do with stipends.</strong> Stipends come from logged, verified hours. Nothing your teammates say about you moves your money, and nothing about your money should shape what you say about them.</p>
</div>
</div>
</section>
<section id="video-reflection-40-points" class="level3">
<h3 class="anchored" data-anchor-id="video-reflection-40-points">Video Reflection (40 points)</h3>
<p>This is where the loop closes. Everything else measures you. This is the one component that asks what you did with the measurement.</p>
<p><strong>Due:</strong> One week after end-of-year feedback is released</p>
<p><strong>Submission:</strong> Record 2 to 4 minutes. Upload to YouTube (unlisted) or Loom and submit the link via Canvas.</p>
<p><strong>Before you record,</strong> re-read three things: your own self-assessment from before the round, your development summary, and your calibration gap.</p>
<p><strong>Prompt.</strong> Four questions.</p>
<ol type="1">
<li><strong>Your prediction.</strong> Before the round you named the axis you expected to rate highest, the one you expected to rate lowest, and the criticism you expected to see. Were you right? Where were you off, and why?</li>
<li><strong>The hardest piece of feedback.</strong> Quote one specific thing a reviewer or your client said. Do you agree with it? What are you doing about it?</li>
<li><strong>The gap.</strong> Your composite and your self-rating differ. Account for the difference. If they matched closely, say what you think you actually got right about reading yourself.</li>
<li><strong>Next time.</strong> If you restarted this engagement knowing what you know now, what would you do differently?</li>
</ol>
<p>Keep it conversational. I am looking for honest self-assessment, not polish. A reflection that admits a miss and says what changes is worth more than one that explains why every criticism was situational.</p>
<p><strong>Rubric:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Criteria</th>
<th>Excellent (10)</th>
<th>Good (7)</th>
<th>Adequate (4)</th>
<th>Weak (0-2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Calibration</strong></td>
<td>Engages the gap between prediction and result directly, and explains it</td>
<td>Notices the gap, explains it thinly</td>
<td>Mentions the gap in passing</td>
<td>Ignores it, or disputes the data instead of engaging it</td>
</tr>
<tr class="even">
<td><strong>Engages feedback</strong></td>
<td>Quotes specific client and peer comments and responds to them</td>
<td>Acknowledges feedback generally</td>
<td>Mentions feedback in passing</td>
<td>Ignores or dismisses</td>
</tr>
<tr class="odd">
<td><strong>Growth mindset</strong></td>
<td>Concrete plan tied to a named axis</td>
<td>General intentions</td>
<td>Minimal forward-looking</td>
<td>No reflection on change</td>
</tr>
<tr class="even">
<td><strong>Clarity</strong></td>
<td>Organized, right length, professional</td>
<td>Minor issues</td>
<td>Rambling or too brief</td>
<td>Unprepared or inappropriate</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Disagreeing with your feedback is allowed and is sometimes correct. What is graded is whether you engage the evidence behind it. “Three people independently said this and I think they are reading one incident wrong, here is why” is a strong answer. “I disagree” is not.</p>
</div>
</div>
</section>
<section id="extra-credit-10-points" class="level3">
<h3 class="anchored" data-anchor-id="extra-credit-10-points">Extra Credit (10 points)</h3>
<p>Complete the BYU end-of-semester student ratings survey to earn 10 extra credit points.</p>
</section>
<section id="grading-scale" class="level3">
<h3 class="anchored" data-anchor-id="grading-scale">Grading Scale</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Grade</th>
<th>%</th>
<th>Points (of 500)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>93–100%</td>
<td>465–500</td>
</tr>
<tr class="even">
<td>A-</td>
<td>90–92%</td>
<td>450–464</td>
</tr>
<tr class="odd">
<td>B+</td>
<td>87–89%</td>
<td>435–449</td>
</tr>
<tr class="even">
<td>B</td>
<td>83–86%</td>
<td>415–434</td>
</tr>
<tr class="odd">
<td>B-</td>
<td>80–82%</td>
<td>400–414</td>
</tr>
<tr class="even">
<td>C+</td>
<td>77–79%</td>
<td>385–399</td>
</tr>
<tr class="odd">
<td>C</td>
<td>73–76%</td>
<td>365–384</td>
</tr>
<tr class="even">
<td>C-</td>
<td>70–72%</td>
<td>350–364</td>
</tr>
<tr class="odd">
<td>D+</td>
<td>67–69%</td>
<td>335–349</td>
</tr>
<tr class="even">
<td>D</td>
<td>63–66%</td>
<td>315–334</td>
</tr>
<tr class="odd">
<td>D-</td>
<td>60–62%</td>
<td>300–314</td>
</tr>
<tr class="even">
<td>E</td>
<td>Below 60%</td>
<td>Below 300</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="credit-hours" class="level2">
<h2 class="anchored" data-anchor-id="credit-hours">Credit Hours</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 38%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Hours/Week</th>
<th>Compensated by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Base commitment</td>
<td>10 hours</td>
<td>3.0 credit hours per semester</td>
</tr>
<tr class="even">
<td>Surge, as client demand requires</td>
<td>Typically +10 hours</td>
<td>Stipend, proportional to logged utilization</td>
</tr>
</tbody>
</table>
<p>Students enroll each semester for a total of 6.0 credit hours across the year. See <a href="#what-you-give-and-what-you-get">What You Give and What You Get</a> for how the stipend is calculated.</p>
</section>
<section id="confidentiality-and-client-data" class="level2">
<h2 class="anchored" data-anchor-id="confidentiality-and-client-data">Confidentiality and Client Data</h2>
<p>Foundry clients share confidential business information: financials, pipelines, customer data, and strategy. This is a condition of the work, and it carries obligations.</p>
<ul>
<li>You will sign the client’s NDA, or the Foundry’s standard mutual NDA, before receiving data.</li>
<li>Client data stays in the approved project repository and approved tools. It does not go into personal accounts, personal cloud storage, or unapproved AI services.</li>
<li>Nothing about the project goes on LinkedIn, in a portfolio, or in a job interview without written client permission. Ask the faculty advisor first, every time.</li>
<li>Deliverables and intellectual property belong to the client, not to you and not to BYU.</li>
<li>When the project ends, you delete local copies of client data.</li>
</ul>
<p>A confidentiality breach is an Honor Code matter and will also end the engagement. Treat this as the professional obligation it is.</p>
</section>
<section id="ai-use-policy" class="level2">
<h2 class="anchored" data-anchor-id="ai-use-policy">AI Use Policy</h2>
<p>You are expected to use AI tools aggressively. That is the point of the Foundry. The obligations that come with it:</p>
<ul>
<li><strong>You own the output.</strong> “The model produced it” is not a defense for a wrong number, a fabricated citation, or an analysis you cannot explain.</li>
<li><strong>Every deliverable must be explainable.</strong> If you cannot walk the client through why the model recommends what it recommends, it is not done.</li>
<li><strong>Client data goes only into approved tools.</strong> See the confidentiality section above.</li>
<li><strong>Disclose method, not apology.</strong> Milestone documentation should say what tools and models you used and how you validated the output.</li>
</ul>
</section>
<section id="instructor-bio" class="level2">
<h2 class="anchored" data-anchor-id="instructor-bio">Instructor Bio</h2>
<p>Scott Murff is an Associate Teaching Professor of Strategy at the BYU Marriott School of Business, where he also serves as faculty advisor and teaches courses on business strategy, decision-making, and artificial intelligence. He brings over 15 years of experience at the intersection of business and technology, having worked as a consultant, product manager, and data scientist.</p>
<p>Prior to joining BYU, Scott spent nearly seven years at McKinsey &amp; Company in roles ranging from analytics specialist consultant to principal product manager, where he led product development and performance management initiatives for Fortune 500 clients. His earlier career includes building forecasting models as a VP at Zions Bancorporation and conducting regulatory research at the U.S. Office of the Comptroller of the Currency.</p>
<p>Scott holds a Master’s degree in Management Science &amp; Engineering from Stanford University and a B.A. in Economics with a minor in Math, from BYU. He is passionate about helping students apply AI, analytics, and strategy to meaningful real-world problems with both rigor and purpose.</p>
</section>
<section id="getting-help" class="level2">
<h2 class="anchored" data-anchor-id="getting-help">Getting Help</h2>
<ul>
<li>Use email or Teams to contact the TAs and Professor Murff</li>
<li>Attend office hours</li>
<li>Bring blockers to studio time. Do not sit on them for a week.</li>
</ul>
</section>
<section id="mission-and-aims" class="level2">
<h2 class="anchored" data-anchor-id="mission-and-aims">Mission and Aims</h2>
<p>The mission of Brigham Young University — founded, supported, and guided by The Church of Jesus Christ of Latter-day Saints: is to assist individuals in their quest for perfection and eternal life. That assistance should provide a period of intensive learning in a stimulating setting where a commitment to excellence is expected and the full realization of human potential is pursued.</p>
<p>BYU seeks to develop students of faith, intellect, and character who have the skills and the desire to continue learning and to serve others throughout their lives.</p>
<p>A BYU education should be (1) spiritually strengthening, (2) intellectually enlarging, and (3) character building, leading to (4) lifelong learning and service.</p>
<p>Building on the foundational Mission and Aims, the Marriott School of Business aspires to transform the world through Christlike leadership by developing leaders of faith, intellect, and character guided by the following 4 values:</p>
<ul>
<li><p><strong>Faith in Christ</strong> - We value deep and abiding faith in Jesus Christ. Our faith gives us the capacity to envision a better future, the confidence to make that future happen, and the courage to act in the face of challenges.</p></li>
<li><p><strong>Integrity in Action</strong> - We value integrity and hold ourselves to the highest moral and ethical standards. Acting with integrity builds trust, strengthens character, and focuses our ambitions on things of eternal consequence.</p></li>
<li><p><strong>Respect for All</strong> - We value respect for all individuals as children of God and recognize the inherent worth, divine potential, and agency of each person. A climate of respect and belonging enhances our learning, facilitates collaboration, and encourages personal growth.</p></li>
<li><p><strong>Excellence</strong> - We value excellence in learning, teaching, research, management, and leadership. An expectation of excellence magnifies our influence and motivates us to continually improve.</p></li>
</ul>
<p>We evaluate our decisions and actions by the impact they will have on the academic experience, professional preparation, character development, emotional well-being, and spiritual growth of our students.</p>
</section>
<section id="honor-code" class="level2">
<h2 class="anchored" data-anchor-id="honor-code">Honor Code</h2>
<p>In keeping with the principles of the BYU Honor Code, students are expected to be honest in all of their academic work. Academic honesty means, most fundamentally, that any work you present as your own must in fact be your own work and not that of another. Violations of this principle may result in a failing grade in the course and additional disciplinary action by the university. Students are also expected to adhere to the Dress and Grooming Standards. Adherence demonstrates respect for yourself and others and ensures an effective learning and working environment. It is the university’s expectation, and every instructor’s expectation in class, that each student will abide by all Honor Code standards. Please call the Honor Code Office at 422-2847 if you have questions about those standards.</p>
</section>
<section id="preventing-responding-to-sexual-misconduct" class="level2">
<h2 class="anchored" data-anchor-id="preventing-responding-to-sexual-misconduct">Preventing &amp; Responding to Sexual Misconduct</h2>
<p>The health and well-being of students is of paramount importance at Brigham Young University. If you or someone you know has experienced sexual harassment (including sexual violence), there are many resources available for assistance.</p>
<p>In accordance with Title IX of the Education Amendments of 1972, BYU prohibits unlawful sex discrimination, including sexual harassment, against any participant in its education programs or activities. The university also prohibits sexual harassment by its personnel and students. Sexual harassment occurs when</p>
<p>a person is subjected to unwelcome sexual speech or conduct so severe, pervasive, and offensive that it effectively denies their ability to access any BYU education program or activity; any aid, benefit, or service of BYU is conditioned on a person’s participation in unwelcome sexual conduct; or a person suffers sexual assault, dating violence, domestic violence, or stalking on the basis of sex. University policy requires all faculty members to promptly report incidents of sexual harassment that come to their attention in any way, including through face-to-face conversations, a written class assignment or paper, class discussion, email, text, or social media post. Incidents of sexual harassment should be reported to the Title IX Coordinator at t9coordinator@byu.edu or (801) 422-8692 or 1085 WSC. Reports may also be submitted online at https://titleix.byu.edu/report or 1-888-238-1062 (24-hours a day).</p>
<p>BYU offers confidential resources for those affected by sexual harassment, including the university’s Sexual Assault Survivor Advocate, as well as a number of non-confidential resources and services that may be helpful. Additional information about Title IX, the university’s Sexual Harassment Policy, reporting requirements, and resources can be found at http://titleix.byu.edu or by contacting the university’s Title IX Coordinator.</p>
</section>
<section id="student-disability" class="level2">
<h2 class="anchored" data-anchor-id="student-disability">Student Disability</h2>
<p>Brigham Young University is committed to providing a working and learning atmosphere that reasonably accommodates qualified persons with disabilities. A disability is a physical or mental impairment that substantially limits one or more major life activities. Whether an impairment is substantially limiting depends on its nature and severity, its duration or expected duration, and its permanent or expected permanent or long-term impact. Examples include vision or hearing impairments, physical disabilities, chronic illnesses, emotional disorders (e.g., depression, anxiety), learning disorders, and attention disorders (e.g., ADHD). If you have a disability which impairs your ability to complete this course successfully, please contact the University Accessibility Center (UAC), 2170 WSC or 801-422-2767 to request a reasonable accommodation. The UAC can also assess students for learning, attention, and emotional concerns. If you feel you have been unlawfully discriminated against on the basis of disability, please contact the Equal Opportunity Office at 801-422-5895, eo_manager@byu.edu, or visit https://hrs.byu.edu/equal-opportunity for help.</p>


</section>

</main> <!-- /main -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

<footer class="book-footer">
  <div class="footer-content">
    <div class="footer-text">
      <a href="https://www.scottmurff.org" target="_blank">© Scott Murff</a>
    </div>
    <div class="footer-icons">
      <a href="https://www.linkedin.com/in/scottdmurff" target="_blank" title="LinkedIn">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="https://github.com/sdmurff" target="_blank" title="GitHub">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </div>
</footer>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../students/07-resources.html" class="pagination-link" aria-label="Resources">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Resources</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../students/02-getting-started.html" class="pagination-link" aria-label="Getting Started">
        <span class="nav-page-text"><span class="chapter-title">Getting Started</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>